import React from 'react';

export default function BriefView({ session }) {
    const brief = session?.interviewerBrief || {};
    const analysis = session?.analysisResults || {};

    return (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">

            {/* AI Header */}
            <div className="bg-gradient-to-r from-gray-800 to-gray-900 px-8 py-6 text-white flex justify-between items-center">
                <div>
                    <h2 className="text-xl font-bold">AI Interviewer Brief</h2>
                    <p className="text-gray-400 text-sm mt-1">Generated by Claude 3.5 Sonnet</p>
                </div>
            </div>

            <div className="p-8 space-y-12">

                {/* Company Profile Section */}
                <section>
                    <h3 className="text-2xl font-bold text-maroon-700 border-b-2 border-gray-100 pb-2 mb-4">
                        Company Profile
                    </h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        <div className="prose prose-sm text-gray-700">
                            <h4 className="font-semibold text-gray-900">Overview</h4>
                            <p>{brief.company_profile?.overview || 'No overview available.'}</p>

                            <h4 className="font-semibold text-gray-900 mt-4">Recent News & Context</h4>
                            <ul className="list-disc pl-5 mt-2 space-y-1">
                                {(brief.company_profile?.recent_news || []).map((news, i) => (
                                    <li key={i}>{news}</li>
                                ))}
                            </ul>
                        </div>

                        <div className="bg-gray-50 rounded-lg p-5 border border-gray-100">
                            <h4 className="font-semibold text-maroon-700 mb-3">Key Strengths</h4>
                            <ul className="space-y-2 mb-6">
                                {(brief.company_profile?.key_strengths || []).map((s, i) => (
                                    <li key={i} className="flex items-start gap-2 text-sm text-gray-800">
                                        <span className="text-green-500 font-bold">✓</span> {s}
                                    </li>
                                ))}
                            </ul>

                            <h4 className="font-semibold text-maroon-700 mb-3">Potential Weaknesses</h4>
                            <ul className="space-y-2">
                                {(brief.company_profile?.potential_weaknesses || []).map((w, i) => (
                                    <li key={i} className="flex items-start gap-2 text-sm text-gray-800">
                                        <span className="text-red-500 font-bold">✗</span> {w}
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </div>
                </section>

                {/* NLP Extraction Data (Comprehend) */}
                {analysis.entities && analysis.entities.length > 0 && (
                    <section className="bg-blue-50/50 rounded-xl p-6 border border-blue-100">
                        <h3 className="text-lg font-bold text-blue-900 mb-3 flex items-center gap-2">
                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"></path></svg>
                            NLP Extracted Entities (Scraped Data)
                        </h3>
                        <div className="flex flex-wrap gap-2">
                            {analysis.entities.slice(0, 15).map((e, idx) => (
                                <span key={idx} className="px-3 py-1 bg-white border border-blue-200 text-blue-800 rounded-full text-xs font-medium shadow-sm">
                                    {e.Text} ({e.Type})
                                </span>
                            ))}
                        </div>
                    </section>
                )}

                {/* Interview Strategy */}
                <section>
                    <h3 className="text-2xl font-bold text-maroon-700 border-b-2 border-gray-100 pb-2 mb-4">
                        Interview Strategy
                    </h3>
                    <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
                        <h4 className="font-bold text-gray-900 mb-2">Primary Objective</h4>
                        <p className="text-gray-700 text-sm mb-6">{brief.interview_strategy?.primary_objective || 'Not defined'}</p>

                        <h4 className="font-bold text-gray-900 mb-3">Conversation Flow</h4>
                        <div className="space-y-4 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-gray-300 before:to-transparent">
                            {(brief.interview_strategy?.conversation_flow || []).map((step, idx) => (
                                <div key={idx} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                                    <div className="flex items-center justify-center w-10 h-10 rounded-full border border-white bg-maroon-100 text-maroon-600 font-bold shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 z-10">
                                        {idx + 1}
                                    </div>
                                    <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
                                        <h5 className="font-bold text-gray-900">{step.phase}</h5>
                                        <p className="text-sm text-gray-600 mt-1">{step.description}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </section>

                {/* Recommended Questions */}
                <section>
                    <h3 className="text-2xl font-bold text-maroon-700 border-b-2 border-gray-100 pb-2 mb-4">
                        Recommended Questions
                    </h3>
                    <div className="space-y-6">
                        {(brief.recommended_questions || []).map((q, idx) => (
                            <div key={idx} className="bg-white border text-left border-gray-200 p-6 rounded-xl shadow-sm hover:shadow-md transition-shadow relative overflow-hidden">
                                <div className="absolute top-0 left-0 w-1 h-full bg-maroon-600"></div>
                                <h4 className="text-lg font-bold text-gray-900 mb-2">{q.question}</h4>
                                <div className="flex flex-wrap gap-2 text-xs mb-4">
                                    <span className="bg-gray-100 text-gray-600 px-2 py-1 rounded font-medium">Category: {q.category}</span>
                                    <span className="bg-maroon-50 text-maroon-700 px-2 py-1 rounded font-medium">Why: {q.rationale}</span>
                                </div>
                                <div className="bg-gray-50 p-4 rounded border border-gray-100 text-sm italic text-gray-700">
                                    <span className="font-bold block not-italic mb-1 text-gray-900">What to look for:</span>
                                    {q.what_to_look_for}
                                </div>
                            </div>
                        ))}
                    </div>
                </section>

            </div>
        </div>
    );
}
